apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
  labels:
    app: nlp-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlp-service
  template:
    metadata:
      labels:
        app: nlp-service
    spec:
      containers:
        - name: nlp-service
          image: content-moderation/nlp-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 50052
          env:
            - name: SERVICE_PORT
              value: "50052"
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: nlp-service
spec:
  selector:
    app: nlp-service
  ports:
    - port: 50052
      targetPort: 50052
  type: ClusterIP
