apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-service
  labels:
    app: rpc-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rpc-service
  template:
    metadata:
      labels:
        app: rpc-service
    spec:
      containers:
        - name: rpc-service
          image: content-moderation/rpc-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 50051
          env:
            - name: SERVICE_PORT
              value: "50051"
            - name: NLP_SERVICE_ADDR
              value: "nlp-service:50052"
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-service
spec:
  selector:
    app: rpc-service
  ports:
    - port: 50051
      targetPort: 50051
  type: LoadBalancer
